"""Core interfaces for TD-GradDFT.

This package re-exports a large surface area. Keep the re-exports lazy so
submodule imports such as ``import td_graddft.reference`` do not pull the
entire stack into memory during process startup.
"""

from __future__ import annotations

from importlib import import_module
from typing import Any


_NAMESPACE_EXPORTS = {
    "gto",
    "scf",
    "dft",
    "tdscf",
    "tddft",
    "neural_xc",
    "nn_rsh",
    "training",
    "workflows",
    "data",
    "data_process",
    "df",
    "traditional_xc",
}

_EXPORTS = {
    "AdiabaticDensityFunctional": "xc",
    "BOHR_TO_ANGSTROM": "geomopt",
    "BoundDM21LikeFunctional": "neural_xc",
    "BoundNeuralXCFunctional": "neural_xc",
    "BoundTrainableRSHFunctional": "dft",
    "BoundRSHFunctionalProtocol": "protocols",
    "BoundXCFunctionalProtocol": "protocols",
    "CLASSIC_XC_SPECS": "traditional_xc",
    "CartesianAO": "data",
    "CartesianBasis": "data",
    "CoordinateUnit": "geomopt",
    "DM21LikeFunctional": "neural_xc",
    "DM21MixingMLP": "neural_xc",
    "DensityNeuralXCFunctional": "neural_xc",
    "DifferentiableSCF": "scf",
    "DifferentiableSCFConfig": "scf",
    "DifferentiableSCFInfo": "scf",
    "EnergyFunction": "geomopt",
    "ExperimentConfig": "workflows",
    "ExperimentPipeline": "workflows",
    "ExperimentRun": "workflows",
    "Functional": "neural_xc",
    "GeometryOptimizationConfig": "geomopt",
    "GeometryOptimizationResult": "geomopt",
    "GradDFTResidualMixingMLP": "neural_xc",
    "GridReference": "reference",
    "GroundStateDatum": "training",
    "GroundStateReference": "types",
    "GroundStateTrainingConfig": "training",
    "HARTREE_TO_EV": "spectra",
    "MissingDependencyError": "upstreams",
    "MoleculeConfig": "api",
    "MoleculeReferenceProtocol": "protocols",
    "NeuralExcitedStateRun": "workflows",
    "NeuralXCFunctional": "neural_xc",
    "NeuralXCHybridFunctional": "neural_xc",
    "NeuralXCMixingMLP": "neural_xc",
    "NeuralXCTrainingConfig": "workflows",
    "OutputConfig": "workflows",
    "OutputPaths": "workflows",
    "PipelineRun": "workflows",
    "PointwiseMLP": "neural_xc",
    "PySCFRSHSpec": "dft",
    "RHFConfig": "scf",
    "RHFResult": "scf",
    "RSHFunctionalTemplate": "dft",
    "RSHParameterBounds": "dft",
    "RSHParameterHead": "dft",
    "RKSConfig": "scf",
    "RKSResult": "scf",
    "RealTimeState": "types",
    "ResolvedRSHParameters": "dft",
    "ReferenceRun": "workflows",
    "ReferenceSpecConfig": "workflows",
    "RestrictedCasidaTDDFT": "tddft",
    "RestrictedFeatureBundle": "jax_libxc",
    "RestrictedMoleculeReference": "reference",
    "SimulationConfig": "workflows",
    "SpectrumGridConfig": "workflows",
    "SpectrumRun": "workflows",
    "SCFXCContributions": "dft",
    "SystemConfig": "workflows",
    "TDAResult": "tddft",
    "TDDFTMatrices": "tddft",
    "TDDFTResult": "tddft",
    "TrainableRSHFunctional": "dft",
    "TrainableRSHFunctionalProtocol": "protocols",
    "TraceableRKSResult": "scf",
    "TraditionalXCFunctional": "traditional_xc",
    "TrainingRun": "workflows",
    "UKSConfig": "scf",
    "UKSResult": "scf",
    "UnrestrictedCasidaTDDFT": "tddft",
    "UnrestrictedMoleculeReference": "reference",
    "UnrestrictedResponseMatrices": "tddft",
    "UnrestrictedTDA": "tddft",
    "UnrestrictedTDAMatrices": "tddft",
    "UnrestrictedTDAResult": "tddft",
    "UnrestrictedTDDFTResult": "tddft",
    "XCFunctionalProtocol": "protocols",
    "BoundLongRangeCorrectedFunctional": "tddft",
    "LongRangeCorrection": "neural_xc",
    "LongRangeCorrectedFunctional": "tddft",
    "LongRangeXCNet": "tddft",
    "b3lyp_component_basis": "jax_libxc",
    "b3lyp_component_coefficients": "jax_libxc",
    "basis_from_pyscf_mol_cart": "data",
    "basis_from_pyscf_spec": "data",
    "benzene_experiment_config": "workflows",
    "benzene_legacy_experiment_config": "workflows",
    "benzene_strict_jax_experiment_config": "workflows",
    "build_hcore": "data.integrals",
    "build_long_range_pair_features": "tddft",
    "build_jk_from_df": "df",
    "build_reference": "api",
    "build_restricted_response_matrices": "tddft",
    "build_unrestricted_response_matrices": "tddft",
    "build_unrestricted_tda_matrices": "tddft",
    "cartesian_angular_tuples": "data",
    "commutator": "realtime",
    "compute_forces": "geomopt",
    "create_train_state": "training",
    "create_train_state_from_molecule": "training",
    "default_lda_coefficient_inputs": "neural_xc",
    "default_lda_energy_density_basis": "neural_xc",
    "density_matching_penalty": "training",
    "density_on_grid": "training",
    "density_on_grid_spin_resolved": "training",
    "density_stationarity_penalty": "training",
    "dm21_like_input_features": "features",
    "dm21_original_input_features": "features",
    "ensure_hermitian": "realtime",
    "eri_element": "data.integrals",
    "eri_tensor": "data.integrals",
    "eri_tensor_screened": "data.integrals",
    "eri_to_df_factors": "df",
    "eval_xc_energy_density": "jax_libxc",
    "evaluate_cartesian_ao": "data",
    "expectation_value": "realtime",
    "gen_tda_vind": "tddft",
    "gen_tdhf_vind": "tddft",
    "ground_state_from_grad_dft_molecule": "upstreams",
    "ground_state_from_pyscf_mean_field": "upstreams",
    "ground_state_mse_loss": "training",
    "has_grad_dft": "upstreams",
    "has_jax_xc": "upstreams",
    "hybrid_coeff": "jax_libxc",
    "kinetic_element": "data.integrals",
    "kinetic_matrix": "data.integrals",
    "lda_from_callable": "xc",
    "lda_from_jax_xc": "xc",
    "legacy_benzene_experiment_config": "workflows",
    "legacy_water_experiment_config": "workflows",
    "liouville_rhs": "realtime",
    "load_jax_xc": "jax_xc_adapter",
    "lorentzian_spectrum": "spectra",
    "make_b3lyp_functional": "traditional_xc",
    "make_classic_xc_functional": "traditional_xc",
    "make_dm21_like_functional": "neural_xc",
    "make_fixed_density_predictor": "training",
    "make_functional": "neural_xc",
    "make_ground_state_loss": "training",
    "make_ground_state_predictor": "training",
    "make_ground_state_train_step": "training",
    "make_lda_functional": "traditional_xc",
    "make_neural_lda_functional": "neural_xc",
    "make_neural_xc_functional": "neural_xc",
    "make_long_range_correction": "neural_xc",
    "make_pbe0_functional": "traditional_xc",
    "make_pbe_functional": "traditional_xc",
    "make_minimal_trainable_rsh_functional": "dft",
    "make_pyscf_rsh_spec": "dft",
    "make_rks_ground_state_energy_fn": "geomopt",
    "make_self_consistent_predictor": "training",
    "make_self_supervised_rsh_loss": "training",
    "nuclear_attraction_element": "data.integrals",
    "nuclear_attraction_matrix": "data.integrals",
    "nuclear_repulsion_energy": "scf",
    "oscillator_strengths": "spectra",
    "overlap_element": "data.integrals",
    "overlap_matrix": "data.integrals",
    "parse_xc": "jax_libxc",
    "pairwise_grid_distances": "tddft",
    "predict_excitation_energies": "training",
    "predict_excitation_spectrum": "training",
    "predict_ground_state_density": "training",
    "predict_ground_state_molecule": "training",
    "predict_ground_state_total_energy": "training",
    "propagate": "realtime",
    "propagate_step": "realtime",
    "put_reference_on_device": "device",
    "put_restricted_reference_on_device": "device",
    "resolve_coefficient_prior_values": "neural_xc",
    "resolve_execution_device": "device",
    "restricted_grid_features": "features",
    "restricted_reference_from_pyscf": "reference_legacy",
    "restricted_reference_from_pyscf_spec_with_jax_rks": "reference_legacy",
    "restricted_reference_from_pyscf_with_jax_rhf": "reference_legacy",
    "restricted_reference_from_pyscf_with_jax_rks": "reference_legacy",
    "restricted_reference_from_spec_with_jax_rks": "reference",
    "unrestricted_reference_from_spec_with_jax_uks": "reference",
    "run_and_report": "workflows",
    "run_and_report_from_spec": "workflows",
    "run_experiment": "workflows",
    "run_geometry_optimization": "geomopt",
    "run_neural_xc_spectrum_pipeline": "workflows",
    "run_neural_xc_spectrum_pipeline_from_spec": "workflows",
    "run_pipeline": "api",
    "run_pipeline_core_from_spec": "workflows",
    "run_reference_from_spec": "workflows",
    "run_rhf": "scf",
    "run_rhf_from_integrals": "scf",
    "run_rks_from_integrals": "scf",
    "run_rks_from_integrals_traceable": "scf",
    "run_rks_ground_state_geometry_optimization": "geomopt",
    "run_spectrum_pipeline": "api",
    "run_uks_from_integrals": "scf",
    "scale_restricted_grid_features": "features",
    "schwarz_bounds": "data.integrals",
    "semilocal_terms": "jax_libxc",
    "solve_casida": "tddft",
    "solve_tda": "tddft",
    "solve_unrestricted_casida": "tddft",
    "solve_unrestricted_tda": "tddft",
    "spin_summed_density_matrix": "upstreams",
    "transition_dipoles": "spectra",
    "unrestricted_reference_from_pyscf": "reference_legacy",
    "unrestricted_reference_from_pyscf_with_jax_uks": "reference_legacy",
    "water_experiment_config": "workflows",
    "water_legacy_experiment_config": "workflows",
    "water_strict_jax_experiment_config": "workflows",
    "compute_long_range_kernel": "tddft",
    "xc_type": "jax_libxc",
}

__all__ = sorted(_NAMESPACE_EXPORTS) + list(_EXPORTS)


def __getattr__(name: str) -> Any:
    if name in _NAMESPACE_EXPORTS:
        module = import_module(f".{name}", __name__)
        globals()[name] = module
        return module
    if name not in _EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(f".{_EXPORTS[name]}", __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
