"""Core interfaces for TD-GradDFT.

This package re-exports a large surface area. Keep the re-exports lazy so
submodule imports do not pull the entire stack into memory during process
startup.
"""

from __future__ import annotations

from importlib import import_module
from typing import Any


_NAMESPACE_EXPORTS = {
    "gto",
    "scf",
    "dft",
    "tdscf",
    "tddft",
    "neural_xc",
    "neural_d",
    "training",
    "workflows",
    "data",
    "data_process",
    "df",
    "traditional_xc",
    "xc_backend",
}

_PUBLIC_EXPORTS = {
    "BOHR_TO_ANGSTROM": "geomopt",
    "BoundNeuralXCFunctional": "neural_xc",
    "BoundXCFunctionalProtocol": "protocols",
    "CLASSIC_XC_SPECS": "traditional_xc",
    "CartesianAO": "data",
    "CartesianBasis": "data",
    "CoordinateUnit": "geomopt",
    "DifferentiableSCF": "scf",
    "DifferentiableSCFConfig": "scf",
    "DifferentiableSCFInfo": "scf",
    "DispersionCorrectedFunctional": "neural_d",
    "DispersionFunctional": "neural_d",
    "EnergyFunction": "geomopt",
    "ExperimentConfig": "workflows",
    "ExperimentPipeline": "workflows",
    "ExperimentRun": "workflows",
    "Functional": "neural_xc",
    "GeometryOptimizationConfig": "geomopt",
    "GeometryOptimizationResult": "geomopt",
    "GradDFTDispersionNetwork": "neural_d",
    "ResidualMixingMLP": "neural_xc",
    "QuadratureGrid": "scf",
    "GroundStateDatum": "training",
    "GroundStateReference": "types",
    "GroundStateTrainingConfig": "training",
    "HARTREE_TO_EV": "spectra",
    "MissingDependencyError": "upstreams",
    "MoleculeConfig": "api",
    "MoleculeRun": "workflows",
    "MoleculeSpecConfig": "workflows",
    "MoleculeReferenceProtocol": "protocols",
    "NeuralExcitedStateRun": "workflows",
    "NeuralXCHybridFunctional": "neural_xc",
    "NeuralXCMixingMLP": "neural_xc",
    "NeuralXCTrainingConfig": "workflows",
    "OutputConfig": "workflows",
    "OutputPaths": "workflows",
    "PipelineRun": "workflows",
    "RHFConfig": "scf",
    "RHFResult": "scf",
    "RKSConfig": "scf",
    "RKSResult": "scf",
    "RestrictedCasidaTDDFT": "tddft",
    "RestrictedFeatureBundle": "xc_backend.jax_libxc",
    "RestrictedMolecule": "scf",
    "SimulationConfig": "workflows",
    "SpectrumGridConfig": "workflows",
    "SpectrumRun": "workflows",
    "SystemConfig": "workflows",
    "TDAResult": "tddft",
    "TDDFTMatrices": "tddft",
    "TDDFTResult": "tddft",
    "TraditionalXCFunctional": "traditional_xc",
    "TrainingRun": "workflows",
    "UKSConfig": "scf",
    "UKSResult": "scf",
    "UnrestrictedCasidaTDDFT": "tddft",
    "UnrestrictedMolecule": "scf",
    "UnrestrictedResponseMatrices": "tddft",
    "UnrestrictedTDA": "tddft",
    "UnrestrictedTDAMatrices": "tddft",
    "UnrestrictedTDAResult": "tddft",
    "UnrestrictedTDDFTResult": "tddft",
    "XCFunctionalProtocol": "protocols",
    "b3lyp_component_basis": "xc_backend.jax_libxc",
    "b3lyp_component_coefficients": "xc_backend.jax_libxc",
    "benzene_experiment_config": "workflows",
    "benzene_strict_jax_experiment_config": "workflows",
    "build_hcore": "data.integrals",
    "build_jk_from_df": "df",
    "build_molecule": "api",
    "build_restricted_response_matrices": "tddft",
    "build_unrestricted_response_matrices": "tddft",
    "build_unrestricted_tda_matrices": "tddft",
    "build_dispersion_pair_inputs": "neural_d",
    "cartesian_angular_tuples": "data",
    "calculate_distances": "neural_d",
    "compute_forces": "geomopt",
    "create_train_state": "training",
    "create_train_state_from_molecule": "training",
    "density_matching_penalty": "training",
    "density_on_grid": "training",
    "density_on_grid_spin_resolved": "training",
    "density_stationarity_penalty": "training",
    "eri_element": "data.integrals",
    "eri_tensor": "data.integrals",
    "eri_tensor_screened": "data.integrals",
    "eri_to_df_factors": "df",
    "eval_xc_energy_density": "xc_backend.jax_libxc",
    "evaluate_cartesian_ao": "data",
    "gen_tda_vind": "tddft",
    "gen_tdhf_vind": "tddft",
    "ground_state_from_grad_dft_molecule": "upstreams",
    "ground_state_mse_loss": "training",
    "has_grad_dft": "upstreams",
    "has_jax_xc": "upstreams",
    "hybrid_coeff": "xc_backend.jax_libxc",
    "kinetic_element": "data.integrals",
    "kinetic_matrix": "data.integrals",
    "load_jax_xc": "xc_backend.jax_xc_adapter",
    "lorentzian_spectrum": "spectra",
    "make_b3lyp_functional": "traditional_xc",
    "make_classic_xc_functional": "traditional_xc",
    "make_dispersion_corrected_functional": "neural_d",
    "make_fixed_density_predictor": "training",
    "make_functional": "neural_xc",
    "make_ground_state_loss": "training",
    "make_ground_state_predictor": "training",
    "make_ground_state_train_step": "training",
    "make_lda_functional": "traditional_xc",
    "make_neural_xc_functional": "neural_xc",
    "make_neural_d_functional": "neural_d",
    "make_pbe0_functional": "traditional_xc",
    "make_pbe_functional": "traditional_xc",
    "make_rks_ground_state_energy_fn": "geomopt",
    "make_self_consistent_predictor": "training",
    "nuclear_attraction_element": "data.integrals",
    "nuclear_attraction_matrix": "data.integrals",
    "nuclear_repulsion_energy": "scf",
    "oscillator_strengths": "spectra",
    "overlap_element": "data.integrals",
    "overlap_matrix": "data.integrals",
    "parse_xc": "xc_backend.jax_libxc",
    "predict_excitation_energies": "training",
    "predict_excitation_spectrum": "training",
    "predict_ground_state_density": "training",
    "predict_ground_state_molecule": "training",
    "predict_ground_state_total_energy": "training",
    "put_molecule_on_device": "device",
    "put_restricted_molecule_on_device": "device",
    "resolve_coefficient_prior_values": "neural_xc",
    "resolve_execution_device": "device",
    "restricted_grid_features": "features",
    "restricted_molecule_from_spec_with_jax_rks": "scf",
    "unrestricted_molecule_from_spec_with_jax_uks": "scf",
    "run_and_report": "workflows",
    "run_and_report_from_spec": "workflows",
    "run_experiment": "workflows",
    "run_geometry_optimization": "geomopt",
    "run_molecule_from_spec": "workflows",
    "run_neural_xc_spectrum_pipeline": "workflows",
    "run_neural_xc_spectrum_pipeline_from_molecule_spec": "workflows",
    "run_neural_xc_spectrum_pipeline_from_spec": "workflows",
    "run_pipeline": "api",
    "run_pipeline_core_from_molecule_spec": "workflows",
    "run_pipeline_core_from_spec": "workflows",
    "run_rhf": "scf",
    "run_rhf_from_integrals": "scf",
    "run_rks_from_integrals": "scf",
    "run_rks_ground_state_geometry_optimization": "geomopt",
    "run_spectrum_pipeline": "api",
    "run_uks_from_integrals": "scf",
    "scale_restricted_grid_features": "features",
    "schwarz_bounds": "data.integrals",
    "semilocal_terms": "xc_backend.jax_libxc",
    "solve_casida": "tddft",
    "solve_tda": "tddft",
    "solve_unrestricted_casida": "tddft",
    "solve_unrestricted_tda": "tddft",
    "spin_summed_density_matrix": "upstreams",
    "transition_dipoles": "spectra",
    "water_experiment_config": "workflows",
    "water_strict_jax_experiment_config": "workflows",
    "xc_type": "xc_backend.jax_libxc",
}

__all__ = sorted(_NAMESPACE_EXPORTS) + list(_PUBLIC_EXPORTS)


def __getattr__(name: str) -> Any:
    if name in _NAMESPACE_EXPORTS:
        module = import_module(f".{name}", __name__)
        globals()[name] = module
        return module
    if name not in _PUBLIC_EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(f".{_PUBLIC_EXPORTS[name]}", __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
